info:
  contact: {}
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: help User Create Account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: User Register
      tags:
      - user
swagger: "2.0"
